import sys
import traceback
import glob
import os
import itertools
import datetime

def help():
    print
    print "Program used to generate many possible reports from provided trade areas."
    print "e.g. [python trade_area.shp output_directory report_type]\n"
    print "\t-trade_area.shp: layer file with appropriate trade area information"
    print "\t-output_directory: directory to store generated report to"
    print "\t-report_type: e.g. 'Demographic and Income Report' or 'Age by Sex Profile'"
    print

try:
  if len(sys.argv) != 4:
    help()
    sys.exit(1)

  trade_area_layer = sys.argv[1]
  output_directory = sys.argv[2]
  report_name = sys.argv[3]

  id_field = 'AREA_ID' #gets generated by ba.drivetime in steps before this 
  report_type = "s.xml"
  store_identifier = "Id"

  print "importing toolbox"
  import arcview
  import arcpy

  arcpy.env.overwriteOutput = True
  print "checking out extensions"
  arcpy.ImportToolbox(r"d:\ArcGIS\Desktop10.0\ArcToolbox\Toolboxes\Business Analyst Tools.tbx")
  arcpy.CheckOutExtension("Business")
  arcpy.CheckOutExtension("Network")

# Define input and output parameters for the Quick Reports tool
  bds = r"d:/ArcGIS/Desktop10.0/Business Analyst/Data/BDS/esri_bg.bds"
  
# Create Quick reports
  print "Running %s for %s." % (report_name, trade_area_layer)
  arcpy.ba.QuickReports(trade_area_layer, id_field, bds, report_name, output_directory, store_identifier, "", "", "", "REPORT_PER_BOUNDARY", "", "INDIVIDUAL_FEATURES", store_identifier, report_type)

  print "checking in extension"
  arcpy.CheckInExtension("Network")
  arcpy.CheckInExtension("Business")

except Exception as e:
  print e
  raise e

exit(0)

